<?php

add_action( 'init', 'your_prefix_register_post_type' );
function your_prefix_register_post_type() {
$labels = [
'name'                     => esc_html__( 'Newell Lectures', 'your-textdomain' ),
'singular_name'            => esc_html__( 'Newell Lecture', 'your-textdomain' ),
'add_new'                  => esc_html__( 'Add New', 'your-textdomain' ),
'add_new_item'             => esc_html__( 'Add New Newell Lecture', 'your-textdomain' ),
'edit_item'                => esc_html__( 'Edit Newell Lecture', 'your-textdomain' ),
'new_item'                 => esc_html__( 'New Newell Lecture', 'your-textdomain' ),
'view_item'                => esc_html__( 'View Newell Lecture', 'your-textdomain' ),
'view_items'               => esc_html__( 'View Newell Lectures', 'your-textdomain' ),
'search_items'             => esc_html__( 'Search Newell Lectures', 'your-textdomain' ),
'not_found'                => esc_html__( 'No newell lectures found.', 'your-textdomain' ),
'not_found_in_trash'       => esc_html__( 'No newell lectures found in Trash.', 'your-textdomain' ),
'parent_item_colon'        => esc_html__( 'Parent Newell Lecture:', 'your-textdomain' ),
'all_items'                => esc_html__( 'All Newell Lectures', 'your-textdomain' ),
'archives'                 => esc_html__( 'Newell Lecture Archives', 'your-textdomain' ),
'attributes'               => esc_html__( 'Newell Lecture Attributes', 'your-textdomain' ),
'insert_into_item'         => esc_html__( 'Insert into newell lecture', 'your-textdomain' ),
'uploaded_to_this_item'    => esc_html__( 'Uploaded to this newell lecture', 'your-textdomain' ),
'featured_image'           => esc_html__( 'Featured image', 'your-textdomain' ),
'set_featured_image'       => esc_html__( 'Set featured image', 'your-textdomain' ),
'remove_featured_image'    => esc_html__( 'Remove featured image', 'your-textdomain' ),
'use_featured_image'       => esc_html__( 'Use as featured image', 'your-textdomain' ),
'menu_name'                => esc_html__( 'Newell Lectures', 'your-textdomain' ),
'filter_items_list'        => esc_html__( 'Filter newell lectures list', 'your-textdomain' ),
'filter_by_date'           => esc_html__( '', 'your-textdomain' ),
'items_list_navigation'    => esc_html__( 'Newell Lectures list navigation', 'your-textdomain' ),
'items_list'               => esc_html__( 'Newell Lectures list', 'your-textdomain' ),
'item_published'           => esc_html__( 'Newell Lecture published.', 'your-textdomain' ),
'item_published_privately' => esc_html__( 'Newell Lecture published privately.', 'your-textdomain' ),
'item_reverted_to_draft'   => esc_html__( 'Newell Lecture reverted to draft.', 'your-textdomain' ),
'item_scheduled'           => esc_html__( 'Newell Lecture scheduled.', 'your-textdomain' ),
'item_updated'             => esc_html__( 'Newell Lecture updated.', 'your-textdomain' ),
'text_domain'              => esc_html__( 'your-textdomain', 'your-textdomain' ),
];
$args = [
'label'               => esc_html__( 'Newell Lectures', 'your-textdomain' ),
'labels'              => $labels,
'description'         => '',
'public'              => true,
'hierarchical'        => false,
'exclude_from_search' => false,
'publicly_queryable'  => true,
'show_ui'             => true,
'show_in_nav_menus'   => true,
'show_in_admin_bar'   => true,
'show_in_rest'        => true,
'query_var'           => true,
'can_export'          => true,
'delete_with_user'    => true,
'has_archive'         => true,
'rest_base'           => '',
'show_in_menu'        => true,
'menu_position'       => 5,
'menu_icon'           => 'dashicons-embed-video',
'capability_type'     => 'post',
'supports'            => ['title', 'thumbnail'],
'taxonomies'          => ['post_tag', 'category'],
'rewrite'             => [
'with_front' => false,
],
];

register_post_type( 'newell-lecture', $args );
}